### ISSUE TITLE
Route configuration should be optional

### ISSUE THREAD

**Issue by echo511** [iPublikuj/assets-loader#2]
A suggestion in config.neon when

```
assetsLoader:
    routes: null
```

the extension wouldn't then be prepending routes to router. I am asking because I want to serve the files via https.

My current workaround is very hacky / ugly:

```
assetsLoader:
    routes:
        assets: http://
        files: http://
```

The routes won't ever match. Then I append custom route in RouterFactory.

Should I prepare a pull or you want to keep current behavior?
